### ISSUE TITLE
Build issues when building with Carthage

### ISSUE THREAD

**Issue by chriscombs** [nodes-ios/Serializable#100]
Not really sure what's going on, as all builds pass in Travis, but when you build using Carthage, the non-iOS platforms fail (swift 2.3)

**Comment by dominik-hadl** [comment]
@chriscombs What is the error message?

**Comment by chriscombs** [comment]
Something about Alcatraz, maybe it's just a local issue for me

**Comment by dominik-hadl** [comment]
Closing for now, if this issue reappears please open a new issue.
