### ISSUE TITLE
Allow the developer to fail the request in implementation even if it returned 200

### ISSUE THREAD

**Issue by mariusc** [nodes-ios/Serializable#101]
There are some bad APIs that return 200, but in the response JSON they return a status code that indicates an error. 

![image](https://cloud.githubusercontent.com/assets/844175/18948186/5d30b572-8636-11e6-91cd-4f92dd59ad9e.png)

It would be nice to have a way of manually checking for that and go to failure if necessary. In the example above, if ReturnCode is different than 0, the Failure case would be called and not the Success one (in the current implementation, it goes to Success).

Maybe returning nil in the Unwrapper should make it go to Failure instead of Success with the empty model.

**Comment by dominik-hadl** [comment]
This needs a bit more investigation as its a bit unclear if this is an extension to Alamofire or something directly applicable to Serpent. 

Anyway, as this seems to be a purely additive feature, I have removed the milestone and we will push it as an update sometime after the first release.

**Comment by chriscombs** [comment]
Re-adding the milestone 😄

**Comment by chriscombs** [comment]
Actually this is solved with #136. If you pass in a custom serializer, you can inspect the result for whatever you want before returning .success or .failure.

**Comment by mariusc** [comment]
Nice! Can we update the README with a small example 😄 ?

**Comment by chriscombs** [comment]
Yeah I'll make an issue for it
