### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by mariusc** [nodes-ios/Serializable#117]
- [x] mention that it was previously known as Serializable
- [x] update the requirements to mention macOS/tvOS/watchOS
- [x] update the code examples in the README to be Swift 3
- [x] maybe mention older versions support in requirements (like in Installation - Carthage)

**Comment by dominik-hadl** [comment]
@mariusc What does the last thing mean? The versions are already mentioned in the README.

**Comment by mariusc** [comment]
![image](https://cloud.githubusercontent.com/assets/844175/20480361/6e66964c-afe2-11e6-82a6-7e17e255d128.png)
@nickskull Yeah, they are, but I think this might turn off people from using Serpent because they will think it doesn't work for Swift 2.3 or 2.2. I know we already write the versions under 'Installation' with Carthage, but I'm thinking it would be  better to have them under Requirements too. But I'm willing to listen to counter-arguments too :D

**Comment by dominik-hadl** [comment]
Ah, I missed the requirements part :D Yeah, I guess we can do that. Although I am pretty sure no one is gonna use 2.2 in a few months.

**Comment by dominik-hadl** [comment]
Also - README should be updated for proper Swift 3 syntax along with new syntax for Alamofire and Cashier extension. Can we add that to the checklist?

**Comment by mariusc** [comment]
@nickskull I updated the checklist
