### ISSUE TITLE
Remove static defaultUnwrapper on Parser

### ISSUE THREAD

**Issue by dominik-hadl** [nodes-ios/Serializable#124]
This will force people to specify an unwrapper manually and prevent issues with a global "magic" unwrapper.

To imagine an example where this is problematic take Module A, where `responseSerializable(completion)` is called with no unwrapper and expects to receive whatever was passed in. Then Module B changes the `Parser.defaultUnwrapper` to something needed for itself. Module A does same action with the `responseSerializable` and now fails because the Parser was changed without it's knowledge.

Only workaround this issue for now was to manully specify the unwrapper everywhere, which in turn eliminates the need for the global unwrapper in the first place. This is a great example of why you should not use a global variable.

**Comment by chriscombs** [comment]
This is a breaking change, right?

**Comment by dominik-hadl** [comment]
Yes, we should first deprecate it and then in v2 delete it.
