### ISSUE TITLE
New comment style, indentation issues

### ISSUE THREAD

**Issue by dominik-hadl** [nodes-ios/Serializable#128]
Serpent is still using the old comment style, which is no longer recommended by Apple, so we should switch to the new standard (`///` on each line).

There's also some indentation issues in the project, which should be fixed. (maybe we could implement SwiftLint?)

**Comment by chriscombs** [comment]
@nickskull  Should this be in 2.0? Or a minor update?

**Comment by dominik-hadl** [comment]
Let's do it along version 2.0 updates.

**Comment by chriscombs** [comment]
Fixed in  #151
