### ISSUE TITLE
Check compatibility with OSX, tvOS, and WatchOS

### ISSUE THREAD

**Issue by chriscombs** [nodes-ios/Serializable#23]
Update the badges and Requirements when applicable

**Comment by dominik-hadl** [comment]
Let's go even further. 
- [ ] Check compatibility with (portability to) Linux :heart:

**Comment by chriscombs** [comment]
😱

**Comment by chriscombs** [comment]
#50 Has added OSX, tvOS, and watchOS support

**Comment by dominik-hadl** [comment]
I'll create a separate ticket for Linux compatibility, as that will most likely require significant changes.
