### ISSUE TITLE
Fix GitHub language detection by ignoring the Prebuild folder

### ISSUE THREAD

**Issue by mariusc** [nodes-ios/Serializable#61]
Serializable is seen as a mainly Objective-C repo. 
Renaming the Prebuild folder to Dependencies should make it be ignored when analysing language, according to https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml

**Comment by dominik-hadl** [comment]
Also, while at it. Try adding this to the .gitattributes file:

```
Serializable.podspec linguist-documentation
```

That should remove that awful 3% Ruby part in language statistics :D

**Comment by mariusc** [comment]
Don't know what happened, but somehow this broke again. Serializable is still viewed as 54% Objective-C. Reopening this issue.
