### ISSUE TITLE
Merge performance tests, move comparison tests to separate repository

### ISSUE THREAD

**Issue by dominik-hadl** [nodes-ios/Serializable#62]
All Serializable related performance tests should be merged into develop and master.

Tests for comparing other frameworks against Serializable should be moved to a different repository, so that this one isn't cluttered. 

---

This will also make sure that performance tests are run in each travis build, which should make it easier for us to spot regressions or improvements.

**Comment by chriscombs** [comment]
Serializable performance tests added in PR #98

**Comment by chriscombs** [comment]
New repo created here: https://github.com/nodes-ios/serializable-performance-comparison
