### ISSUE TITLE
NSURLs are not parsed properly from a dictionary if it has a source type of NSURL

### ISSUE THREAD

**Issue by kasperwelner** [nodes-ios/Serializable#70]
Serializable saves it as a NSURL when encoding, resulting in the parser not parsing it correctly when deserialising from disk (Looks like it enters the mapped overload for StringInitializable and fails when it gets out a NSURL instead of a String)

**Comment by chriscombs** [comment]
Fixed https://github.com/nodes-ios/Serializable/pull/71

**Comment by Joker666** [comment]
Is the change in the latest release in Cocoapods? Coz I am using the cocoapods version and I have problem when deserializing NSURL, it becomes nil

**Comment by dominik-hadl** [comment]
@Joker666 Unfortunately we haven't been able to update our podspec to the latest version yet, as we were having some issues with dependencies. We are working on it though and we'll keep you updated! :)
