### ISSUE TITLE
One final master/dev tag and make swift-3.0 new master

### ISSUE THREAD

**Issue by chriscombs** [nodes-ios/Serializable#97]
I'm not sure if we're ready to break everyone's cartfiles yet, but we should coordinate across the other frameworks as well. 

The master/dev branches do not have any features that swift-3.0 doesn't; the most recent commits to those are just updating to swift 2.3 and fixing travis. swift-3.0 has newer fixes and updates.

**Comment by dominik-hadl** [comment]
I think now it's the right time, as we're updating most tools and frameworks anyway. So I'd rather break it now than later on. Just make sure that you note it in the README.

**Comment by Joker666** [comment]
I don't see any commit in master after 2.3 update, did you guys update the library for Swift 3.0?

**Comment by dominik-hadl** [comment]
@Joker666 Hey, everything should be updated under the tag `0.12.0-beta.1`, but we will be merging everything ASAP :) The framework will also be renamed, as there is a lot of frameworks with this name and it confuses people a bit. So we will do both of these changes at once and hopefully it's gonna be last breaking release.

**Comment by Joker666** [comment]
Thanks :)

**Comment by dominik-hadl** [comment]
As soon as Travis finishes on #115 , Swift 3.0 support will be merged to master and new tag (version 1.0 🎉 ) will be added.
